### ISSUE TITLE
When Trying to Create Site: File Already Exists

### ISSUE THREAD

**Issue by gfs** [FuLagann/csharp-docs-generator#25]
I'm encountering : https://github.com/microsoft/OAT/pull/13 for context.
`Exception calling "ExtractToDirectory" with "2" argument(s): "The file 
'D:\a\OAT\OAT\__temp-e2db8a4c-5087-4f27-aaa5-bd96c009c12d\libs\microsoft.csharp\4.5.0\_rels\.rels' already exists."`.  This message repeats for a large number of files.

It ends up finally failing out with ` Cannot read property 'keywords' of undefined
    at eval (eval at compile (D:\a\_actions\FuLagann\csharp-docs-generator\v1.0\node_modules\ejs\lib\ejs.js:626:12), <anonymous>:12:19)`

## Yml used
```yml
name: Generate and Publish Documentation

on:
  pull_request:
    branches: [ main ]
jobs:
  generate-docs:
    runs-on: windows-latest
    name: Generate Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.300"
      - name: Generate Documentation
        uses: FuLagann/csharp-docs-generator@v1.0
        with:
          build-tasks: dotnet build
          cleanup-tasks: dotnet clean
          binaries: OAT/bin/Debug/netstandard2.1/OAT.dll
          output-path: docs/api
          skip-git: true
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/api
```

## Error Message
```
Exception calling "ExtractToDirectory" with "2" argument(s): "The file 
'D:\a\OAT\OAT\__temp-e2db8a4c-5087-4f27-aaa5-bd96c009c12d\libs\microsoft.csharp\4.5.0\_rels\.rels' already exists."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException
 
Error: The process 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\FuLagann\csharp-docs-generator\v1.0\node_modules\@actions\exec\lib\toolrunner.js:561:25)
    at ExecState.CheckComplete (D:\a\_actions\FuLagann\csharp-docs-generator\v1.0\node_modules\@actions\exec\lib\toolrunner.js:544:18)
    at ChildProcess.<anonymous> (D:\a\_actions\FuLagann\csharp-docs-generator\v1.0\node_modules\@actions\exec\lib\toolrunner.js:444:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
