### ISSUE TITLE
Push to branch not working

### ISSUE THREAD

**Issue by Morasiu** [FuLagann/csharp-docs-generator#28]
I have a simple yaml

```yaml
on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: windows-latest
    name: Generate C# Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.300"
      - name: C# Documentation Generator
        uses: FuLagann/csharp-docs-generator@v1.0
        with:
          build-tasks: dotnet build
          cleanup-tasks: dotnet clean, cp -rf docs/* .
          binaries: Clockify.Net\bin\Debug\netstandard2.0\Clockify.Net.dll
          output-path: docs
          branch-name: gh-pages
          user-email: morasiu2@gmail.com
          user-name: Morasiu
          project-details-json: project-details.json
```

As you can see I don't have `skip-git` property.

I don't see any `git push`  in my git action log

```
... // HTML generation
HTML generation complete!
Running: dotnet clean
... // dotnet clean here
Running: cp -rf docs/* .
"C:\Program Files\Git\usr\bin\cp.exe" -rf docs/* .
```

Okay. I see in the source code, that git push isn't logged. (Maybe it should be?)

Anyway... I don't see branch `gh-pages` in my repo.

@update

WIth manually created branch `gh-pages` it is also **not** working.

Also I don't see `index.html` 
```
Running: ls docs/api
"C:\Program Files\Git\usr\bin\ls.exe" docs/api
--navigation.html
clockify.net.clockifyclient.html
// other HTML files
css
js
```

@Update
Looks like my action is using an old version CsharpGenerator because I don't see

```
`Created index page!`
```
But it is in source code [here](https://github.com/FuLagann/csharp-docs-generator/blob/5055b760275efd8d33032855c17c88de2d8c9289/src/generate.ts#L97)

How can I force using new version?
